### ISSUE TITLE
AttribureError: module 'papitools' has no attribute 'Papitools'

### ISSUE THREAD

**Issue by rsaiprashanth** [vreddhi/PAPITools#2]
when I was trying a update sureroute object using `python CustomPAPIActions.py -updateSRTO -config="MSCI-Example-Config-Test" -version=4`. I got an error:

```
Establishing Connection
Traceback (most recent call last):
  File "CustomPAPIActions.py", line 367, in <module>
    PapiToolsObject = papitools.Papitools(access_hostname=access_hostname)
AttributeError: module 'papitools' has no attribute 'Papitools'
```

Seemingly there is no Papitools in other module?

**Comment by vreddhi** [comment]
There is papitools.py under papitools folder, i have heard people reporting this issue. Will look into this.

**Comment by vreddhi** [comment]
You can try now. I fixed this. Also you may want to create a branch under your name so that it is easy for you to pull the latest code :).

**Comment by rsaiprashanth** [comment]
Works good :) I have forked your repo undermine and have it in sync with your repo.
