### ISSUE TITLE
Adding a new behavior

### ISSUE THREAD

**Issue by rsaiprashanth** [vreddhi/PAPITools#3]
I've written this code block for adding a new behavior under default rule. This would make sense?
```
propertyJson = PapiToolsObject.getPropertyRules(session,property_name,version).json()
    newBehaviors = []

    for behavior in propertyJson['rules']['behaviors']:
        if behavior['name'] != behaviorName:
            newBehaviors.append(behavior)

    propertyJson['rules']['behaviors'] = newBehaviors
    updateObjectResponse = PapiToolsObject.uploadRules(session, propertyJson,property_name, version)
```

Though when I ran the command no errors/no intended output. Can you assist where I went wrong?

**Comment by vreddhi** [comment]
if behavior['name'] != behaviorName:
            newBehaviors.append(behavior)

The above code snippet is **adding all** existing behaviors as is, if 'behaviorName' is something new !!

If you are interested to add a behavior which is unique and new. Try coding the below pseudo-code:

propertyJson = PapiToolsObject.getPropertyRules(session,property_name,version).json()

newBehaviorStructure = {
<name> : 'name',
options : { 
              ....
              ...
           }
}

behaviorName = newBehaviorStructure['name']

newBehaviors = propertyJson['rules']['behaviors']
if behaviorName not in behavior:
    newBehaviors.append(newBehaviorStructure)

propertyJson['rules']['behaviors'] = newBehaviors

**Comment by rsaiprashanth** [comment]
Thanks, @vreddhi. Here is the working block for adding new behaviour RUM under default rule. Can you add this new feature to Master?

```
if args.addBehavior:
    property_name = args.Configuration
    version = args.Version
    PapiToolsObject = Papitools(access_hostname=access_hostname)
    print("\nHang on... while we download the json data.. ")
    print("\nHang on... We are almost set, fetching the rules now.. This will take time..\n")
    propertyJson = PapiToolsObject.getPropertyRules(session,property_name,version).json()

    newBehaviorStructure = {
    'name' : 'realUserMonitoring',
    'options': {
        'enabled' : True
        }
    }

    behaviorName = newBehaviorStructure['name']

    newBehaviors = propertyJson['rules']['behaviors']
    if behaviorName not in newBehaviors:
        newBehaviors.append(newBehaviorStructure)

    propertyJson['rules']['behaviors'] = newBehaviors

    print("\nHang on... We are almost set, Updating with the rules now.. This will again take time..\n")
    updateObjectResponse = PapiToolsObject.uploadRules(session, propertyJson,property_name, version)
    print("\nLooks like it is done\n")
```

**Comment by vreddhi** [comment]
Sure. I will do this. Feels good to see you getting the hang of this already. Appreciated Sai.
